### ISSUE TITLE
Issue on logs page - log.body.messages is empty

### ISSUE THREAD

**Issue by psmyrdek** [HamedMP/CursorLens#23]
I'm struggling with the following issue:
![image](https://github.com/user-attachments/assets/d4bb2c88-8512-470f-bfd2-6140b4cf4de5)

The issue is caused by the incorrect encoding of log body that is getting added to the database. While reading, it cannot be converted into a correct JSON.

Happy to contribute based on @HamedMP suggestions.

**Comment by HamedMP** [comment]
Thanks for detecting it @psmyrdek, I'd appreciate a PR for it, thanks for noticing it and offering your help 🙇🏼

**Comment by HamedMP** [comment]
A fix for it is coming today, checking Docker setup, will ping you over here 🙌🏼
