### ISSUE TITLE
Trouble using ollama, no logs at all!

### ISSUE THREAD

**Issue by arthur-yh** [HamedMP/CursorLens#29]
when useing ollama as my local llm providers, I run `ollama run codellama`, and I set http://localhost:11434/v1 in Cursor setting as endpoint;

well, I can use ollama normally, but http://localhost:3000/ show nothing at all
<img width="1716" alt="image" src="https://github.com/user-attachments/assets/20fc92e1-5daf-4032-9c68-d2bbc07e69f8">

**Comment by HamedMP** [comment]
Hi, 

Cursor requires a `HTTPS` link (and even locally signed HTTPS doesn't work), so it needs to be a publicly accessible URL. 

Can you try it with using `ngrok`?

**Comment by arthur-yh** [comment]
well, using ngrok is absolutely ok, But in my company, use ngrok is not support.

Thanks for polling up https questions, I will try make a proxy to it.

**Comment by HamedMP** [comment]
Oh I understand, feel free to use any alternative one or your own proxy. Let me know how it goes and if we can add something to the repo based on it

**Comment by arthur-yh** [comment]
Ok, if there is anything new, I will leave a message back.
