### ISSUE TITLE
Is there a way to capture the code completion request?

### ISSUE THREAD

**Issue by shouldnotappearcalm** [HamedMP/CursorLens#30]
Is there a way to capture completion requests?

I can see the conversation requests between me and the model in Logs, but I can't see the completion-related requests. Is there a way to capture this?

**Comment by HamedMP** [comment]
Hi, which part of Cursor are you referring to as Completion? Is it Cursor Tab? 

In that case, Tab is using Cursor's own model and it's not using OpenAI models.

**Comment by shouldnotappearcalm** [comment]
Yes, it is the code completion of tab.

Ok, it seems there is no way to capture it, I will think of other ways.

Thank you
