### ISSUE TITLE
Failing to update API endpoint in Cursor Settings

### ISSUE THREAD

**Issue by tanys123** [HamedMP/CursorLens#9]
Everything works fine except error while verifying the endpoint in Cursor Settings.

It just doesn't work, but the `curl` version show by Cursor does work.
<img width="867" alt="Screenshot 2024-08-19 at 8 53 15 AM" src="https://github.com/user-attachments/assets/10131507-9bb6-4fb2-bde7-cd2910d5933a">

Anything I miss out?

**Comment by HamedMP** [comment]
Hi, 

No need to press Verify as the model is set on the Configuration page and the api key is the one in ENV variable. 

You only need to override the OpenAI base URL and choose any gpt model in Cursor so the OpenAI URL is shown. 

final checklist: 
- the base url should be updated
- the toggle should be on 
- The key is not important  - and verify wouldn’t work 


You can test with: cmd+L and send a no context chat to a gpt model, it should be routed through CursorLens. 


Let me know if you have more questions.

**Comment by nightscape** [comment]
Does the API endpoint have to be an NGrok URL, or can I also use localhost?
The latter would allow using Cursor with local models even when no Internet connection is available.

**Comment by HamedMP** [comment]
Thanks for the question @nightscape , Cursor requires `https` models, so the current workaround is `ngrok` or similar service, but we're looking into ways to do self-signing certificates to run localhost with `https` to fix this issue and be completely offline/off the grid 🚀

**Comment by tanys123** [comment]
Thanks @HamedMP 👍. Just tried again and it works! 
However, the toggle button only show if you have successful verify before, so you somehow still have to click Verify once withe valid Key then only change the base URL.
